INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (1, 'Alicate', 'José Da Brita', 364, (32.50))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (2, 'Areia_Lavada', 'José Da Brita', 8516, (180.00))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (3, 'Bloco de Pedra', 'José Da Brita', 592, (45.00))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (4, 'Broca para Concreto', 'José Da Brita', 418, (7.50))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (5, 'Capacete de Proteção', 'José Da Brita', 826,(29.99))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (6, 'Chave de Fenda', 'José Da Brita', 581, (18.50))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (7, 'Chave de Teste', 'José Da Brita', 926, (27.50))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (8, 'Chave Inglesa', 'José Da Brita', 531, (14.50))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (9, 'Cimento', 'José Da Brita', 782, (78.00))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (10, 'Escada de Madeira', 'José Da Brita', 825, (89.00))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (11, 'Fita Dupla Face', 'José Da Brita', 579, (3.75))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (12, 'Furadeira', 'José Da Brita', 741, (199.90))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (13, 'Lâmpada LED', 'José Da Brita', 963, (8.50))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (14, 'Lixa de Ferro', 'José Da Brita', 942, (2.25))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (15, 'Luvas de Proteção', 'José Da Brita', 642, (5.00))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (16, 'Máscara de Respiração', 'José Da Brita', 912, (4.75))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (17, 'Martelo de Borracha', 'José Da Brita', 652, (29.90))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (18, 'Nível a Laser', 'José Da Brita', 236, (129.90))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (19, 'Prego Grande', 'José Da Brita', 853, (2.50))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (20, 'Prego Pequenos', 'José Da Brita', 852, (1.50))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (21, 'Porta de Madeira', 'José Da Brita', 456, (130.00))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (22, 'Serrote', 'José Da Brita', 159, (65.00))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (23, 'Telha Ceramica', 'Fabio Compensado Naval', 25, (11.00))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (24, 'Tinta Acrílica', 'Fabio Compensado Naval', 658, (125.00))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (25, 'Serra Circular', 'Fabio Compensado Naval', 785, (159.00))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (26, 'Tábua de Madeira', 'Fabio Compensado Naval', 357, (42.00))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (27, 'Vassoura', 'Fabio Compensado Naval', 669, (12.00))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (28, 'Esponja de Limpeza', 'Fabio Compensado Naval', 873, (4.50))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (29, 'Rodo', 245, 'Fabio Compensado Naval', (8.99))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (30, 'Óculos de Sol', 'Fabio Compensado Naval', 732, (10.99))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (31, 'Pano de Limpeza', 'Fabio Compensado Naval', 521, (2.99))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (32, 'Protetor Auricular', 'Fabio Compensado Naval', 357, (8.50))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (33, 'Limpador Multiuso', 'Fabio Compensado Naval', 986, (7.50))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (34, 'Parafusadeira', 'Fabio Compensado Naval', 4628, (159.90))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (35, 'Parafuso Sextavado 4mm', 'Fabio Compensado Naval', 1598, (2.00))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (36, 'Escada Aluminio', 'Fabio Compensado Naval', 1529, (299.90))
INSERT INTO [dbo].[Produto] ([IdProd], [NomeProd], [NomeFanta], [CodProd], [Preco]) VALUES (37, 'Areia_Grossa', 'Fabio Compensado Naval', 4126, (350.00))